### ISSUE TITLE
Install in virtualenv fails because it does not include system libraries 

### ISSUE THREAD

**Issue by CristianCantoro** [lokkju/pyspatialite#18]
(I am using Ubuntu 12.10 on a x86_64 system)
## Steps to reproduce
1. make sure that all the needed libraries are installed. For reference on a Ubuntu system this means:
   `apt-get install python-dev`
   `apt-get install libgoes-dev`
   `apt-get install libproj-dev`
   `apt-get install libsqlite3-dev`
   this [blog post](http://martin-paulo.blogspot.it/2013/06/spatialite-and-me.html) has more information for a system install of pyspatialite on Ubuntu 12.04, 12.10 and 13.04
2. create a virtualenv named "pyspatialite-test"
   `mkvirtualenv pyspatialite-test`
3. try to `pip install spatialite`

Install should fail with:
`__main__.HeaderNotFoundException: cannot find proj_api.h, bailing out`
(complete pip log is [here](http://pastebin.com/76mED6cy))

A simple search reveals that proj_api.h is present:
    `$ locate proj_api.h`
    `/usr/include/proj_api.h`

The problem is in the setup script because neither the variable `include_dirs` nor `self.compiler.include_dirs` contain `/usr/include`

The two following include paths (on Linux system) should be added: 
- `/usr/local/include`
- `/usr/include`

Adding them manually to `setup.py` solves the issue and the package install successfully.

**Comment by jameshiebert** [comment]
For those that are still having this problem, you should just be able to add the required `CFLAGS` to your `pip` invocation on the command line. `pip` will honor the environment variables.

```bash
$ CFLAGS=-I/usr/include .env/bin/pip install pyspatialite
```

**Comment by mgallagher** [comment]
Has anyone been able to figure this out on OSX? `proj_api.h` is nowhere to be found for me. Is there something else that needs to be installed? I'm running El Capitan public beta 2.

**Comment by fitnr** [comment]
You'll need the Proj and GEOS libraries. For OS X, the easiest way to install them is with [homebrew](http://brew.sh): `brew install proj geos`. Once that's done, use `brew info geos proj` to find the install locations, ans specify the `include` folder in the `CFLAGS` option, as above. The command will look something like:

```
CFLAGS="-I/usr/local/Cellar/proj/4.9.2/include -I/usr/local/Cellar/geos/3.5.0/include" \
    pip install pyspatialite
```
