### ISSUE TITLE
Does not find libgeos

### ISSUE THREAD

**Issue by sk1p** [lokkju/pyspatialite#21]
On my system (Debian sid, amd64), there is no `/usr/lib/libgeos.so`, only `/usr/lib/libgeos-3.4.2.so`. This of course results in an error: `/usr/bin/ld: cannot find -lgeos` (tested with `pyspatialite-3.0.1-alpha-0`).

Manually changing the `check_lib` line for geos and geosadvanced to the following 

```
self.check_lib(ext,"GEOSTopologyPreserveSimplify","geos_c","'libgeos_c' is required but it doesn't seem to be installed on this system.",["m","geos-3.4.2"])
```

makes pyspatialite build successfully. A possible solution is to use the output of `geos-config` for finding the right lib:

```
$ geos-config --libs
-L/usr/lib -lgeos-3.4.2
```

**Comment by micahcochran** [comment]
That is a Debian packaging problem. I fixed it by doing this:

/usr/lib$ sudo ln -s libgeos-3.4.2.so lingeoslibgeos.so
