### ISSUE TITLE
installing the 3.0 alpha with pip fails to find proj.h in /usr/local/include on Mac OS 10.9

### ISSUE THREAD

**Issue by rful011** [lokkju/pyspatialite#22]
Subject says it all.

**Comment by hjwp** [comment]
+1

**Comment by strk** [comment]
confirmed also happens on ubuntu 14.04:
```
__main__.HeaderNotFoundException: cannot find proj_api.h, bailing out
```

The header is on the system, in standard location:
```
[strk@cdb:~] grep VERSION /usr/include/proj_api.h
#define PJ_VERSION 480
```

**Comment by FedericoRessi** [comment]
The same on OSX 10.11.6.

```bash
grep VERSION /usr/local/include/proj_api.h
#define PJ_VERSION 493
```

**Comment by FedericoRessi** [comment]
I was able to install it. Having installed project dependencies using brew, then I had to apply a patch on top of branch 3.0.1-amalgamation.


```
diff --git a/setup.py b/setup.py
index 3eddd35..dc96ccd 100644
--- a/setup.py
+++ b/setup.py
@@ -44,6 +44,10 @@ pyspatialite is an interface to the SQLite 3.x embedded relational database engi
 It is almost fully compliant with the Python database API version 2.0 also
 exposes the unique features of SQLite and spatialite."""
 
+COMMON_INCLUDE_DIRS = [
+    '/usr/local/include',
+    '/usr/include']
+
 class DocBuilder(Command):
     description = "Builds the documentation"
     user_options = []
@@ -169,6 +173,8 @@ class OverrideSystemIncludeOrderBuildCommand(build_ext):
         include_dirs.extend(self.strip_includes(self.compiler.linker_so))
         include_dirs.extend(self.strip_includes(self.compiler.linker_exe))
         include_dirs.extend(self.strip_includes(self.compiler.preprocessor))
+        include_dirs.extend([
+            idir for idir in COMMON_INCLUDE_DIRS if os.path.isdir(idir)])
         self.compiler.include_dirs.extend(self.uniq(include_dirs))
 
         if self.with_proj4:
```

I had also to remove sqlite3.h and sqlite3extra.h from my /usr/local/include folder.

**Comment by ozak** [comment]
Same issue on OS X 10.12. Any progress? Have not tried @FedericoRessi work around, since it wasn't clear to me what the steps followed were (also not sure if removing the last couple of files is safe or will break something else).

**Comment by ozak** [comment]
The previous error comes from ``pip install pyspatialite``. On the other hand, using

    pip install git+https://github.com/lokkju/pyspatialite.git#egg=pyspatialite

gives another error

    Collecting pyspatialite from git+https://github.com/lokkju/pyspatialite.git#egg=pyspatialite
      Cloning https://github.com/lokkju/pyspatialite.git to /private/var/folders/74/f8jv43x13mn4r07rw06crj4w0000gp/T/pip-build-NweW7X/pyspatialite
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/private/var/folders/74/f8jv43x13mn4r07rw06crj4w0000gp/T/pip-build-NweW7X/pyspatialite/setup.py", line 79, in <module>
            class OverrideSystemIncludeOrderBuildCommand(build_ext):
          File "/private/var/folders/74/f8jv43x13mn4r07rw06crj4w0000gp/T/pip-build-NweW7X/pyspatialite/setup.py", line 88, in OverrideSystemIncludeOrderBuildCommand
            ('with-spatialit-init-ex=', None, "use spatialite_init_ex() instead of deprecated spatialite_init() method (default: False)")
        TypeError: 'tuple' object is not callable
