### ISSUE TITLE
Move from deprecated spatialite_init() method to spatialite_init_ex()

### ISSUE THREAD

**Issue by sebastic** [lokkju/pyspatialite#24]
pyspatialite has become unusable in Debian after libspatialite was rebuilt with libproj 4.9.1, because it still uses the deprecated spatialite_init() method which is intrinsically thread unsafe and now causes segfaults.

This issue was first reported for the spatialite-bin package in [Debian Bug #785091](https://bugs.debian.org/785091), but it affects all software built on top of libspatialite.

SpatiaLite upstream has deprecated the spatialite_init() method in favour of the spatialite_init_ex() method some time ago. See the related discussion on the [gdal-dev](http://lists.osgeo.org/pipermail/gdal-dev/2015-May/041806.html), [qgis-developer](http://lists.osgeo.org/pipermail/qgis-developer/2015-May/037824.html) & [spatialite-users](https://groups.google.com/d/msg/spatialite-users/83SOajOJ2JU/sgi5fuYAVVkJ) lists for backgrounds and porting instructions.

**Comment by lokkju** [comment]
fixed in #25
