### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by tobias47n9e** [lokkju/pyspatialite#27]
The command:

```
python3 -m pip install pyspatialite
```

fails with this traceback:

```
Collecting pyspatialite
  Using cached pyspatialite-3.0.1-alpha-0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-y10vod4q/pyspatialite/setup.py", line 66
        print "Is sphinx installed? If not, try 'sudo easy_install sphinx'."
                                                                           ^
    SyntaxError: Missing parentheses in call to 'print'
```

Seems like the print-functions and some other things need updating for Python 3.

**Comment by filipkral** [comment]
I have the same problem.
But is it just the setup.py that fails or is pyspatialite not ready for Python 3 in other parts as well?

**Comment by sebastic** [comment]
There seem to be some interesting changes in @SeanHayes fork: 

https://github.com/SeanHayes/pyspatialite/commits/python3-compatibility

**Comment by SeanHayes** [comment]
I never got that finished though, the C part of the code would raise Segmentation Faults somewhere along the line, probably related to str/unicode/byte changes. Feel free to fork my fork. Maybe I'll take another crack at it this weekend.

**Comment by EmilStenstrom** [comment]
Could the patches from @qgis be incorporated to this repo? I suspect more and more people will stumble into this problem as Python 3 usage keeps growing.

**Comment by sebastic** [comment]
I think this projects needs a new maintainer to work on these issues.

**Comment by lokkju** [comment]
@sebastic - agreed. I haven't had the time, and I'm not working with spatialite lately.  Anyone would like to take it over is welcome to.  I can either grant permissions, or I'll put in a point to your branch and sync occasionally.

**Comment by girardea** [comment]
Any update since then? I tried installing @qgis copy as @EmilStenstrom suggested, but could not make it work. Any workaround solution would be great! Unfortunately, I can't say I would be able to do it by myself.

**Comment by sebastic** [comment]
I've posted a thread on the spatialite-users list asking for a new maintainer:

 https://groups.google.com/forum/#!topic/spatialite-users/o0jUwMUqx_g

**Comment by girardea** [comment]
Great, and it seems that apparently pyspatialite is not needed anymore... though I could not make the extension loading work on Windows 64bit. Will try and ask for advice on the Google Groups thread.

**Comment by SeanHayes** [comment]
@girardea What do you mean it's not needed anymore? Is the feature set supported out of the box now?

**Comment by girardea** [comment]
Not exactly, but you just have to load the extension and there you go. Just
follow the Google Groups link in the message above and look for the reply
by Sandro there. He explains it with all needed details.
