### ISSUE TITLE
Error build in Arch Linux

### ISSUE THREAD

**Issue by samtux** [lokkju/pyspatialite#28]
I get the next error building in Arch Linux with Spatialite version 4.3.0. 

  -> pyspatialite-3.0.1-alpha-0.tar.gz ha sido encontrado 
  -> setup.cfg ha sido encontrado 
==> Validando los archivos source con md5sums…
    pyspatialite-3.0.1-alpha-0.tar.gz ... Aprobado
    setup.cfg ... Aprobado
==> Extrayendo las fuentes…
  -> Extrayendo pyspatialite-3.0.1-alpha-0.tar.gz con bsdtar
==> Eliminando el directorio $pkgdir/…
==> Iniciando build()…
/usr/lib/python2.7/site-packages/setuptools/dist.py:331: UserWarning: Normalizing '3.0.1-alpha-0' to '3.0.1a0'
  normalized_version,
running build
running build_py
running build_ext
gcc -pthread -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python2.7 -c /tmp/pj_init_plust4U7KT.c -o tmp/pj_init_plust4U7KT.o
/tmp/pj_init_plust4U7KT.c:1:1: aviso: el tipo de devolución por defecto es ‘int’ [-Wimplicit-int]
 main (int argc, char *_argv) {
 ^~~~
/tmp/pj_init_plust4U7KT.c: En la función ‘main’:
/tmp/pj_init_plust4U7KT.c:2:5: aviso: declaración implícita de la función ‘pj_init_plus’ [-Wimplicit-function-declaration]
     pj_init_plus();
     ^~~~~~~~~~~~
gcc -pthread tmp/pj_init_plust4U7KT.o -L/usr/lib -L/usr/lib -L/usr/lib -L/usr/lib -lm -lproj -lspatialite -o a.out
gcc -pthread -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python2.7 -c /tmp/GEOSTopologyPreserveSimplifyS7NwXv.c -o tmp/GEOSTopologyPreserveSimplifyS7NwXv.o
/tmp/GEOSTopologyPreserveSimplifyS7NwXv.c:1:1: aviso: el tipo de devolución por defecto es ‘int’ [-Wimplicit-int]
 main (int argc, char *_argv) {
 ^~~~
/tmp/GEOSTopologyPreserveSimplifyS7NwXv.c: En la función ‘main’:
/tmp/GEOSTopologyPreserveSimplifyS7NwXv.c:2:5: aviso: declaración implícita de la función ‘GEOSTopologyPreserveSimplify’ [-Wimplicit-function-declaration]
     GEOSTopologyPreserveSimplify();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -pthread -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python2.7 -c /tmp/iconvRfbbif.c -o tmp/iconvRfbbif.o
/tmp/iconvRfbbif.c:1:1: aviso: el tipo de devolución por defecto es ‘int’ [-Wimplicit-int]
 main (int argc, char *_argv) {
 ^~~~
/tmp/iconvRfbbif.c: En la función ‘main’:
/tmp/iconvRfbbif.c:2:5: aviso: declaración implícita de la función ‘iconv’ [-Wimplicit-function-declaration]
     iconv();
     ^~~~~
building 'pyspatialite._spatialite' extension
gcc -pthread -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -DVERSION="3.0.1" -DSQLITE_ENABLE_RTREE=1 -DNDEBUG=1 -DSPL_AMALGAMATION=1 -DMODULE_NAME="spatialite.dbapi2" -DHAVE_PROJ_API_H=1 -DHAVE_GEOS_C_H=1 -Iamalgamation/libspatialite-amalgamation-3.0.1/headers -I/usr/include -I/usr/include/python2.7 -c src/module.c -o build/temp.linux-x86_64-2.7/src/module.o -DOMIT_FREEXL
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:650:8: error: redefinición de ‘struct sqlite3_file’
 struct sqlite3_file {
        ^~~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:818:16: nota: se definió originalmente aquí
 typedef struct sqlite3_file sqlite3_file;
                ^~~~~~~~~~~~
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:745:8: error: redefinición de ‘struct sqlite3_io_methods’
 struct sqlite3_io_methods {
        ^~~~~~~~~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:820:16: nota: se definió originalmente aquí
   const struct sqlite3_io_methods *pMethods;  /_ Methods for an open file */
                ^~~~~~~~~~~~~~~~~~
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:1219:8: error: redefinición de ‘struct sqlite3_vfs’
 struct sqlite3_vfs {
        ^~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:1198:16: nota: se definió originalmente aquí
 typedef struct sqlite3_vfs sqlite3_vfs;
                ^~~~~~~~~~~
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:1516:8: error: redefinición de ‘struct sqlite3_mem_methods’
 struct sqlite3_mem_methods {
        ^~~~~~~~~~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:1493:16: nota: se definió originalmente aquí
 typedef struct sqlite3_mem_methods sqlite3_mem_methods;
                ^~~~~~~~~~~~~~~~~~~
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:5791:8: error: redefinición de ‘struct sqlite3_module’
 struct sqlite3_module {
        ^~~~~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:5012:16: nota: se definió originalmente aquí
 typedef struct sqlite3_module sqlite3_module;
                ^~~~~~~~~~~~~~
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:5922:8: error: redefinición de ‘struct sqlite3_index_info’
 struct sqlite3_index_info {
        ^~~~~~~~~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:5010:16: nota: se definió originalmente aquí
 typedef struct sqlite3_index_info sqlite3_index_info;
                ^~~~~~~~~~~~~~~~~~
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:5925:10: error: redefinición de ‘struct sqlite3_index_constraint’
   struct sqlite3_index_constraint {
          ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:5121:10: nota: se definió originalmente aquí
   struct sqlite3_index_constraint {
          ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:5932:10: error: redefinición de ‘struct sqlite3_index_orderby’
   struct sqlite3_index_orderby {
          ^~~~~~~~~~~~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:5128:10: nota: se definió originalmente aquí
   struct sqlite3_index_orderby {
          ^~~~~~~~~~~~~~~~~~~~~
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:5937:10: error: redefinición de ‘struct sqlite3_index_constraint_usage’
   struct sqlite3_index_constraint_usage {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:5133:10: nota: se definió originalmente aquí
   struct sqlite3_index_constraint_usage {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:6035:8: error: redefinición de ‘struct sqlite3_vtab’
 struct sqlite3_vtab {
        ^~~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:5009:16: nota: se definió originalmente aquí
 typedef struct sqlite3_vtab sqlite3_vtab;
                ^~~~~~~~~~~~
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:6059:8: error: redefinición de ‘struct sqlite3_vtab_cursor’
 struct sqlite3_vtab_cursor {
        ^~~~~~~~~~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:5011:16: nota: se definió originalmente aquí
 typedef struct sqlite3_vtab_cursor sqlite3_vtab_cursor;
                ^~~~~~~~~~~~~~~~~~~
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:6554:8: error: redefinición de ‘struct sqlite3_mutex_methods’
 struct sqlite3_mutex_methods {
        ^~~~~~~~~~~~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:5710:16: nota: se definió originalmente aquí
 typedef struct sqlite3_mutex_methods sqlite3_mutex_methods;
                ^~~~~~~~~~~~~~~~~~~~~
In file included from src/statement.h:29:0,
                 from src/module.c:25:
/usr/include/sqlite3.h:7280:8: error: redefinición de ‘struct sqlite3_pcache_methods’
 struct sqlite3_pcache_methods {
        ^~~~~~~~~~~~~~~~~~~~~~
In file included from src/connection.h:33:0,
                 from src/module.c:24:
amalgamation/libspatialite-amalgamation-3.0.1/headers/spatialite/sqlite3.h:6325:16: nota: se definió originalmente aquí
 typedef struct sqlite3_pcache_methods sqlite3_pcache_methods;
                ^~~~~~~~~~~~~~~~~~~~~~
error: command 'gcc' failed with exit status 1
==> ERROR: Se produjo un fallo en build().
    Cancelando…

**Comment by Grigory75** [comment]
Hello! 
I encountered the same problem in Fedora 28 (Mate) and fixed it. 
To fix it you should build pyspatialite from source code. 

1.Download it from git (git clone), 
2.open file lib/pyspatialite/dbapi2.py,
CHANGE SOURCE CODE LINE 
version_info = tuple([int(x) for x in version.split(".")])
TO
version_info = tuple([int(x) for x in "4.0.3".split(".")]) 

instead of "4.0.3" use the real version of your libspatialite, installed in OS.
than build and install pyspatialite by the following commands:
CFLAGS="-I/usr/include -mcet" python setup.py build
sudo CFLAGS="-I/usr/include -mcet" python setup.py install

To test installation follow the next scenario:
1. run python
2. execute commands:

import pyspatialite.dbapi2 as db

con = db.connect(':memory:')

# Test that the spatialite extension has been loaded:
cursor = con.execute('SELECT sqlite_version(), spatialite_version()')
print cursor.fetchall()
# Output should be something like: [(u'3.7.9', u'3.0.1')]
