### ISSUE TITLE
Unclear licensing

### ISSUE THREAD

**Issue by lokkju** [lokkju/pyspatialite#3]
_From [d.paleino](https://code.google.com/u/113387367459930843307/) on April 23, 2011 00:26:10_

Hello,
I'm packaging pyspatialite for Debian, and I have problems with the license of this software.

In the tarball, there is a LICENSE file containing the zlib/libpng license, with copyright 2004-2007 Gerhard Häring.

PKG-INFO contains Lokkju Brennr as author, and doesn't mention Gerhard Häring at all.

The homepage says the license is MIT, and the only contributor is Lokkju Brennr.

Would you please clarify the situation?

Thanks,
David

_Original issue: http://code.google.com/p/pyspatialite/issues/detail?id=3_

**Comment by sebastic** [comment]
David Paleino uploaded pyspatialite to Debian in 2012: https://tracker.debian.org/pkg/pyspatialite

The zlib license is documented in the Debian package [copyright](http://anonscm.debian.org/cgit/pkg-grass/pyspatialite.git/tree/debian/copyright) file.

The license could be mentioned in the README.md to make the situation clearer.
